### ISSUE TITLE
UndefVarError: .+ not defined

### ISSUE THREAD

**Issue by ValeriiBaidin** [ericproffitt/TopicModelsVB.jl#24] opened 2020-05-28 01:41 UTC
julia ver. 1.1.1
```
UndefVarError: .+ not defined

Stacktrace:
 [1] update_elbo!(::LDA) at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/LDA.jl:91
 [2] LDA(::TopicModelsVB.Corpus, ::Int64) at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/LDA.jl:42
 [3] top-level scope at In[35]:1
```

**Comment by ericproffitt** [comment] 2020-05-28 01:46
Hi Valerii,

Can you please provide me with a minimal code sample with which I can replicate this error.

**Comment by ValeriiBaidin** [comment] 2020-05-28 01:52
I don't have problem on my computer. It works perfectly. But on server, I have these errors. 
I will give little example later. That code is too big to copy. 
`model = LDA(corpus_t, 10)`

**Comment by ericproffitt** [comment] 2020-05-28 01:59
If it works on your computer, but not on your server, then it may have to do with the Linux distribution of Julia.

If I'm not able to replicate the error on my computer, then it may be difficult or impossible for me to fix.

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:01
> If it works on your computer, but not on your server, then it may have to do with the Linux distribution of Julia.
> 
> If I'm not able to replicate the error on my computer, then it may be difficult or impossible for me to fix.

Yes, I understand it.

But do you know your code in the lines? What can cause the error?

**Comment by ericproffitt** [comment] 2020-05-28 02:04
So that line is modified by an internal macro. The code is,

```julia
@positive model.phi[1] = model.beta_old[:,terms] .* exp.(model.Elogtheta_old[d])
```

Which should result in the following expression,

```julia
model.phi[1] = EPSILON .+ model.beta_old[:,terms] .* exp.(model.Elogtheta_old[d])
```

**Comment by ericproffitt** [comment] 2020-05-28 02:05
Are you able to to perform coordinate-wise addition of a scalar and an array on your server's version of Julia?

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:06
Maybe it can be useful

```
WARNING: Method definition additive_logistic(Array{#s17, 2} where #s17<:Real) in module TopicModelsVB at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/utils.jl:113 overwritten at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/utils.jl:135.
WARNING: Method definition binomlogpdf(Real, Real, Real) in module StatsFuns at /home/vbaidin/.julia/packages/StatsFuns/CXyCV/src/distrs/binom.jl:19 overwritten in module TopicModelsVB at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/utils.jl:164.
WARNING: Method definition entropy(Distributions.Dirichlet{T} where T<:Real) in module Distributions at /home/vbaidin/.julia/packages/Distributions/ZJ0hQ/src/multivariate/dirichlet.jl:118 overwritten in module TopicModelsVB at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/utils.jl:168.
WARNING: Method definition (::Type{TopicModelsVB.Corpus})(Array{TopicModelsVB.Document, 1}) in module TopicModelsVB at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/Corpus.jl:76 overwritten at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/Corpus.jl:77.
WARNING: Method definition (::Type{TopicModelsVB.Corpus})(TopicModelsVB.Document) in module TopicModelsVB at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/Corpus.jl:78 overwritten at /home/vbaidin/.julia/packages/TopicModelsVB/09DyQ/src/Corpus.jl:79.
```

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:08
this is a simple exercise,  with the same problem 

```
c= Corpus([Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),
            Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),
            Document([7,7,7]),Document([7,7,7]),Document([7,7,7]),Document([7,7,7])],
            vocab = split("1 2 3 4 5 6 7"))
model = LDA(c, 2)
```

**Comment by ericproffitt** [comment] 2020-05-28 02:10
```Julia
c= Corpus([Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),
            Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),
            Document([7,7,7]),Document([7,7,7]),Document([7,7,7]),Document([7,7,7])],
            vocab = split("1 2 3 4 5 6 7"))
model = LDA(c, 2)
```

This code works fine for me on the Mac distribution of Julia 1.4.2.

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:11
> ```julia
> c= Corpus([Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),Document([1,2,3]),
>             Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),Document([4,5,6]),
>             Document([7,7,7]),Document([7,7,7]),Document([7,7,7]),Document([7,7,7])],
>             vocab = split("1 2 3 4 5 6 7"))
> model = LDA(c, 2)
> ```
> 
> This code works fine for me on the MacOS distribution of Julia 1.4.2.

it works on Julia 1.3 on my PC.

So is the problem of Julia 1.1.1? Can I do something to patch it?

**Comment by ericproffitt** [comment] 2020-05-28 02:16
If you are not able to upgrade your server's version of Julia (which may or may not fix the problem), then patching your copy of TopicModelsVB.jl will be difficult if the problem is the element-wise addition operator, since that operator is used in many places in the code.

So even if you manually fix this particular line, the error will just then pop up somewhere else. Can you please run the following code on your server, and let me know if it works:

```julia
3 .+ [1 2; 3 4]
```

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:18
> If you unable to upgrade your server's version of Julia (which may or may not fix the problem), then patching your copy of TopicModelsVB.jl will be difficult if the problem is the element-wise addition operator, since that operator is used in many places in the source code.
> 
> So even if you manually fix this particular line, the error will just then pop up somewhere else. Can you please run the following code on your server, and let me know if it works:
> 
> ```julia
> 3 .+ [1 2; 3 4]
> ```
Thank you for your help.

it works perfectly.

**Comment by ericproffitt** [comment] 2020-05-28 02:19
Ok, now can you please try this code:

```julia
EPSILON = 1

macro positive(expr::Expr)
	"Add EPSILON to a numerical variable or array during variable assignment."

	if (expr.head == :.) || (expr.head == :ref)
		expr_out = :(:($($expr)) .+= EPSILON)
	
	elseif expr.head == :(=)
		expr_out = :(:($($(expr.args[1]))) = EPSILON .+ :($($(expr.args[2]))))
	end

	return expr_out
end

@positive x = 3
```

The result should be `4`.

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:22
> Ok, now can you please try this code:
> 
> ```julia
> EPSILON = 1
> 
> macro positive(expr::Expr)
> 	"Add EPSILON to a numerical variable or array during variable assignment."
> 
> 	if (expr.head == :.) || (expr.head == :ref)
> 		expr_out = :(:($($expr)) .+= EPSILON)
> 	
> 	elseif expr.head == :(=)
> 		expr_out = :(:($($(expr.args[1]))) = EPSILON .+ :($($(expr.args[2]))))
> 	end
> 
> 	return expr_out
> end
> 
> @positive x = 3
> ```
> 
> The result should be `4`.
> 
> And then if that works, try this:
> 
> ```julia
> @positive x = [1 2; 3 4]
> ```

the same error
```
UndefVarError: .+ not defined

Stacktrace:
 [1] top-level scope at In[6]:15
```

**Comment by ericproffitt** [comment] 2020-05-28 02:22
Which gave you the error, `@positive x=3` or `@positive x = [1 2; 3 4]`?

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:23
> Which gave you the error, `@positive x = 3` or `@positive x = [1 2; 3 4]`?
The first, I can't even define the macro

**Comment by ericproffitt** [comment] 2020-05-28 02:29
Ok, so this is something I will need to discuss with the Julia Dev team, and then I can get back to you hopefully with a solution at a future date.

In the mean time, my only suggestion is to try upgrading Julia to the latest version (if you can), as that may fix the issue.

**Comment by ValeriiBaidin** [comment] 2020-05-28 02:30
Thank. 
Unfortunately, I can't update it right now. =(

Thank you for your help.

**Comment by ValeriiBaidin** [comment] 2020-05-28 03:49
```
macro test_macro(e::Expr)
    return esc( :( ones(size($e)[1]) .+ $e) )
end

@test_macro [1 2 ; 3 4]

```

This code works on Julia ver 1.1.1

**Comment by ericproffitt** [comment] 2020-05-28 04:28
You might try patching the _macros.jl_ file by replacing the `positive` macro with the following code:

```julia
macro positive(expr::Expr)
	"Add EPSILON to a numerical variable or array during variable assignment."

	if (expr.head == :.) || (expr.head == :ref)
		expr_out = :($expr .+= EPSILON)
	
	elseif expr.head == :(=)
		expr_out = :($(expr.args[1]) = EPSILON .+ $(expr.args[2]))
	end

	return expr_out
end
```

This appears to be working for my tests, but I'll need to test it further before I open a PR.

**Comment by ValeriiBaidin** [comment] 2020-05-28 15:14
> Try out the following code on your command line:
> 
> ```julia
> macro positive(expr::Expr)
> 	"Add EPSILON to a numerical variable or array during variable assignment."
> 
> 	if (expr.head == :.) || (expr.head == :ref)
> 		expr_out = :($expr .+= EPSILON)
> 	
> 	elseif expr.head == :(=)
> 		expr_out = :($(expr.args[1]) = EPSILON .+ $(expr.args[2]))
> 	end
> 
> 	return expr_out
> end
> ```
> 
> If it works, then you could try patching the _macros.jl_ file by replacing the `positive` macro with the above.
> 
> It appears to be working for my preliminary tests, but I'll need to test it further before I open a PR.

Unfortunately,  it doesn't work.
But the next code works!!!!


```
EPSILON = 1
macro positive(expr::Expr)
	"Add EPSILON to a numerical variable or array during variable assignment."
	if (expr.head == :.) || (expr.head == :ref)
		expr_out = esc( :($expr .+= EPSILON))
	
	elseif expr.head == :(=)
		expr_out = esc( :($(expr.args[1]) = EPSILON .+ $(expr.args[2])) )
	end
	return expr_out
end

```

**Comment by ericproffitt** [comment] 2020-05-28 18:08
Ok so I did find this related [dicussion](https://github.com/JuliaLang/julia/issues/23221) of unresolved issues in Julia's metaprogramming functionality.

If escaping the return value is what's fixing the problem for you, then a potential patch would be to go into _macros.jl_ and replace `return expr_out` with `return esc(expr_out)` for all the macros which return a value.

**Comment by ericproffitt** [comment] 2020-05-28 22:36
Ok, so I've modified the offending macros.

You can see the changes made here:
https://github.com/ericproffitt/TopicModelsVB.jl/commit/fcd6f8d6d4cf93a5c74b18ba33098dc8473323e9

Could you let me know if this fixes the problem for you?

**Comment by ValeriiBaidin** [comment] 2020-05-29 00:16
> Ok, so I've modified the offending macros.
> 
> You can see the changes made here [fcd6f8d](https://github.com/ericproffitt/TopicModelsVB.jl/commit/fcd6f8d6d4cf93a5c74b18ba33098dc8473323e9).
> 
> Could you let me know if this fixes the problem for you?

thank you.

Shall I replace only macro.jl file, or should I update the whole package?

**Comment by ericproffitt** [comment] 2020-05-29 00:20
The changes have been committed to the master branch.

So if you just run,

```julia
pkg> add https://github.com/ericproffitt/TopicModelsVB.jl
```

Then you should be good to go, no need to modify the _macros.jl_ file yourself.

**Comment by ValeriiBaidin** [comment] 2020-05-29 00:25
> The changes have been committed to the master branch.
> 
> So if you just run,
> 
> ```julia
> pkg> add https://github.com/ericproffitt/TopicModelsVB.jl
> ```
> 
> Then you should be good to go, no need to modify the _macros.jl_ file yourself.

Thank you, I will check a lit bit later.

Thank you so much

**Comment by ericproffitt** [comment] 2020-06-01 23:45
I'm going to close this issue, if you're still having problems with the macro functionality, please feel free to reopen.

**Closed by ericproffitt** 2020-06-01 23:45 UTC
